version: '3.1'
services:
  app:
    build: .
    ports:
      - '8100:8100'
      - '35729:35729'
    volumes:
      - .:/opt/my-music
      - notused:/opt/my-music/node_modules
    command: ionic serve --all
    stdin_open: true
    tty: true
volumes:
  notused: